# Generated by Django 4.2.7 on 2025-09-23 08:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        # --- Booking: champs "invité" déjà présents en DB => STATE-ONLY ---
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='booking',
                    name='guest_name',
                    field=models.CharField(
                        max_length=120, null=True, blank=True,
                        help_text='Nom du client invité (si non connecté)'
                    ),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='booking',
                    name='guest_phone',
                    field=models.CharField(
                        max_length=32, null=True, blank=True,
                        help_text='Téléphone du client invité'
                    ),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='booking',
                    name='guest_email',
                    field=models.EmailField(
                        max_length=254, null=True, blank=True,
                        help_text='Email du client invité (pour confirmations)'
                    ),
                ),
            ],
        ),

        # --- Driver: champs déjà présents en DB => STATE-ONLY ---
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='driver',
                    name='notifications_enabled',
                    field=models.BooleanField(
                        default=True,
                        help_text='Le chauffeur souhaite-t-il recevoir des notifications ?'
                    ),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='driver',
                    name='telegram_chat_id',
                    field=models.CharField(
                        max_length=50, null=True, blank=True,
                        help_text='Chat ID Telegram du chauffeur pour les notifications'
                    ),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='driver',
                    name='telegram_username',
                    field=models.CharField(
                        max_length=100, null=True, blank=True,
                        help_text='Username Telegram du chauffeur (optionnel)'
                    ),
                ),
            ],
        ),

        # --- Invoice: sent_at déjà présent en DB => STATE-ONLY ---
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='invoice',
                    name='sent_at',
                    field=models.DateTimeField(null=True, blank=True),
                ),
            ],
        ),

        # --- Booking.user: devient nullable + SET_NULL (modif RÉELLE) ---
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(
                to=settings.AUTH_USER_MODEL,
                on_delete=django.db.models.deletion.SET_NULL,
                null=True, blank=True, related_name='bookings',
                help_text='Client qui a fait la réservation (peut être null pour un invité)',
            ),
        ),

        # --- Ajustements existants (RÉELS) ---
        migrations.AlterField(
            model_name='driver',
            name='phone_number',
            field=models.CharField(
                validators=[django.core.validators.RegexValidator(
                    regex=r'^\+?1?\d{9,15}$',
                    message="Le numéro de téléphone doit être au format: '+999999999'. 9 à 15 chiffres autorisés."
                )],
                max_length=17, unique=True, default='',
                help_text='Numéro de téléphone unique du chauffeur',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(
                validators=[django.core.validators.RegexValidator(
                    regex=r'^\+?1?\d{9,15}$',
                    message="Le numéro de téléphone doit être au format: '+999999999'. 9 à 15 chiffres autorisés."
                )],
                max_length=17, default='', blank=True,
                help_text='Numéro de téléphone au format international',
            ),
        ),
    ]
