# Generated by Django 4.2.7 on 2025-06-09 14:05

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_address', models.CharField(help_text='Adresse de départ', max_length=255)),
                ('pickup_latitude', models.DecimalField(decimal_places=8, help_text='Latitude du point de départ', max_digits=10)),
                ('pickup_longitude', models.DecimalField(decimal_places=8, help_text='Longitude du point de départ', max_digits=11)),
                ('destination_address', models.CharField(help_text='Adresse de destination', max_length=255)),
                ('destination_latitude', models.DecimalField(decimal_places=8, help_text='Latitude du point de destination', max_digits=10)),
                ('destination_longitude', models.DecimalField(decimal_places=8, help_text='Longitude du point de destination', max_digits=11)),
                ('estimated_price', models.DecimalField(decimal_places=2, help_text='Prix estimé de la course', max_digits=8)),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, help_text="Prix final facturé. Pour l'instant égal à l'estimated_price.", max_digits=8, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('CONFIRMED', 'Confirmée'), ('DRIVER_ASSIGNED', 'Chauffeur assigné'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminée'), ('CANCELLED', 'Annulée')], default='PENDING', help_text='Statut actuel de la réservation', max_length=20)),
                ('scheduled_time', models.DateTimeField(help_text='Heure prévue pour la course')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Heure de fin de course', null=True)),
                ('driver', models.ForeignKey(blank=True, help_text='Chauffeur assigné à la course', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='core.driver')),
                ('user', models.ForeignKey(help_text='Client qui a fait la réservation', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'db_table': 'bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(help_text='Numéro de facture unique', max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Montant HT de la facture', max_digits=8)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Montant de la TVA', max_digits=8)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Montant TTC de la facture', max_digits=8)),
                ('status', models.CharField(choices=[('GENERATED', 'Générée'), ('SENT', 'Envoyée'), ('PAID', 'Payée')], default='GENERATED', help_text='Statut de la facture', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_path', models.CharField(blank=True, help_text='Chemin vers le fichier PDF de la facture', max_length=255)),
                ('booking', models.OneToOneField(help_text='Réservation associée à cette facture', on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='core.booking')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'db_table': 'invoices',
                'ordering': ['-generated_at'],
            },
        ),
    ]
