# Generated by Django 4.2.7 on 2025-09-23 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_booking_guest_email_booking_guest_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='luggage_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='Nombre de bagages'),
        ),
        migrations.AddField(
            model_name='booking',
            name='passengers',
            field=models.PositiveSmallIntegerField(default=1, help_text='Nombre de passagers'),
        ),
        migrations.AddField(
            model_name='booking',
            name='vehicle_type',
            field=models.CharField(choices=[('eco', 'Eco'), ('berline', 'Berline'), ('van', 'Van'), ('goldwing', 'Goldwing')], default='eco', help_text='Type de véhicule demandé', max_length=20),
        ),
    ]
